#spring.application.name=forum_system

spring:
  application:
    name: forum_system
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: 2001
    driver-class-name: com.mysql.cj.jdbc.Driver
#    spring:
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # springfox-swagger 兼容性配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    default-property-inclusion: NON_NULL # 序列化时，不给null时序列化


mybatis:
  configuration: # 配置打印 MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 配置驼峰自动转换
  mapper-locations: classpath:mapper/**/*.xml

# 服务器配置
server:
  port: 58080 # 自定义端口号

# 日志
logging:
  pattern:
    dateformat: MM-dd HH:ss # 日期显示格式
  level:
    root: info # 日志的默认级别
#    com.fly.demo: debug # 指定包下的日志级别 开发环境的日志目录
  file:
    path: /log/forum_001 # 生产环境的日志目录
#    path: E:/Github_Coding/log/forum_system # 日志保存的路径


fly-forum:
  login:
    url: sign-in.html # 未登录情况下 强制跳转页面
  index:
    board-num: 9 # 板块显示的个数
