#spring.application.name=forum_system

spring:
  application:
    name: forum_system
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 2001
    driver-class-name: com.mysql.cj.jdbc.Driver
    spring:
      jpa:
        hibernate:
          ddl-auto: update
mybatis:
  configuration: # 配置打印 MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 配置驼峰自动转换
  mapper-locations: classpath:mapper/**/*.xml

# 服务器配置
server:
  port: 58080 # 自定义端口号

# 日志
logging:
  pattern:
    dateformat: MM-dd HH:ss # 日期显示格式
  level:
    root: info # 日志的默认级别
    com.fly.demo: debug # 指定包下的日志级别
  file:
    path: E:/Github_Coding/log/forum_system # 日志保存的路径
